module.exports.descriptors = [
    "Forest",
    "Mountain",
    "Little",
    "Horse",
    "Alpaca",
    "Capibara",
    "Orchard",
    "Rabbit",
    "Guinea pig",
    "Pony",
    "Sunflower",
    "Cornflower",
    "Daisy",
    "Malva",
    "Orchid",
    "Willow",
    "Green",
    "Riverwood",
    "Birchwood"
]

module.exports.places = [
    "Village",
    "Valley",
    "Cabin",
    "Holidays",
    "Farm",
    "Fields",
    "Farmstay",
    "Station",
    "Meadows",
    "Springs",
    "Adventure",
    "Park",
    "Eden",
    "Ranch",
    "Sanctuary",
    "Cottage",
    "Vineyard",
    "Retreat",
    "Backcountry",
    "River",
    "Creek",
    "Spring"
]
